### PR TITLE
Add Valendas theme

### PR DESCRIPTION
**Pull request by stefonarch**
The last ones of my themes, promise.

### CODE REVIEW

**Comment by stefonarch** [comment]
Oh, I see... forgot to clean the .svg files

**Comment by tsujan** [comment]
> forgot to clean the .svg files

If they're already small, it isn't important.

**Comment by tsujan** [comment]
Added a commit for SVG cleanup.

**Comment by tsujan** [comment]
BTW, I noticed that many themes don't have left arrows for menus:

```css
QMenu::left-arrow {
    image: url(arrow-left.svg);
}
```
Left arrows are used with RTL languages.

**Comment by stefonarch** [comment]
> BTW, I noticed that many themes don't have left arrows for menus:

I jiust tested the panel with `LANG=ar ` and every theme and found the  arrow was present in menus , except system theme. 
But you're the RTL master.

**Comment by stefonarch** [comment]
> They may use the default arrow, not the theme arrow.

True, did just check the presence of the arrow. Should we make a PR for that?

**Comment by tsujan** [comment]
> Should we make a PR for that?

Yes, please! You could flip right arrows horizontally in Inkscape, save them with "left" instead of "right", and add a "left" block to the stylesheets.

The Kvantum theme already has it, I think.

**Comment by tsujan** [comment]
Oh, sorry, you said "we". I run away from RTL for a while; so, it's only you.

**Comment by tsujan** [comment]
Off topic:

I'll start to make pre-release changes soon. I hope everything will be ready in April 15, especially `libqtxdg`. If not, we could wait a week or so. If some things aren't ready until then, we could make point releases later.

If there's any objection to this plan, please tell me! IMHO, regular releases are important.

**Comment by stefonarch** [comment]
April 15 would be good sure, but better wait a week instead of making point releases after some days ;)

**Comment by stefonarch** [comment]
> The Kvantum theme already has it, I think.

I started the PR for RTL arrows and noticed the "arrow-*-selected"  which is nice, so I applied it to Arch-colors where it works fine, then I noticed that the selected arrows are not displayed in Kvantum theme, I've found no reason for that... already flipped to much panel and themes now.

**Comment by tsujan** [comment]
> then I noticed that the selected arrows are not displayed in Kvantum theme

Nice catch! Your finding helped me find a workaround for two bugs in Qt stylesheets. I'll make a PR for Kvantum theme to circumvent both issues, one of which is about selected menu arrows.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-themes/pull/64

**Comment by tsujan** [comment]
I added a commit to clean up the new SVG arrows. Also, made the left arrows mirror images of the right arrows with respect to the middle vertical line (their horizontal positions were a little off).

**Comment by tsujan** [comment]
An unimportant detail (which you could safely ignore):

You have this:

```css
QMenu::item {
   color: #e6e8e8;
   border: 1px solid transparent;
   padding: 5px 30px 5px 10px;
   background:rgba(5, 0, 0, 55%);
   border-right: 3px solid transparent;
}
```

The padding isn't symmetrical horizontally. The right padding is 30px, while the left one is 10px. That results in an asymmetry between LTR and RTL. I propose `padding: 5px 20px 5px 20px;`.

I think similar asymmetries exist in some other themes.

**Comment by stefonarch** [comment]
Thanks! yes, I thought there could be some sort of those asymmetries in the themes, looking at the arabic panel. 
But could it be that  the qss is read "the other way round" with RT? I made a test, the first is with the "asymmetric" original code and basically it looks ok,  just flipped. , the second with your proposal:
schermata-7 apr 19:24

schermata-7 apr 19:23

**Comment by stefonarch** [comment]
> I added a commit to clean up the new SVG arrows. Also, made the left arrows mirror images of the right arrows with respect to the middle vertical line (their horizontal positions were a little off).

Thanks! I'm afraid you'll have to fix all the left SVG arrows I made for the other themes....

**Comment by tsujan** [comment]
> But could it be that the qss is read "the other way round" with RT?

Sadly, no. Qt's RTL is a source of headache.

> the first is with the "asymmetric" original code and basically it looks ok, just flipped. , the second with your proposal:

Both are OK.

> I'm afraid you'll have to fix all the left SVG arrows I made for the other themes....

SVG cleanup isn't so important for LXQt themes because they have only a few SVG elements. It's important for SVG icon sets or SVG-based themes (like those of Kvantum style).

I cleaned up those images out of force of habit ;) I've patched an old version of SVG Cleaner and, after using it, do some manual cleanup. Might clean up other images latter.

**Comment by tsujan** [comment]
The minor problem in your second screenshot is among the bugs I worked around in https://github.com/lxqt/lxqt-themes/pull/64. Since you don't change the padding, it won't show up with your theme.

Its cause is that Qt's stylesheet style has an incorrect calculation of menu-item width. The bug will become almost invisible if a large enough padding and/or border width is used. Apparently, the combination of 30 and 10 hides it in your theme, while 20 and 20 doesn't.

Feel free to merge the PR if you're satisfied with it. And thanks for adding another theme to the collection!

**Comment by stefonarch** [comment]
Just found and installed svgcleaner, will fix some.
All is done except system theme, I've no clue there. Adding an image could result in invisible arrows. In RTL mainmenu no arrows seen, in right click menu an arrow on the wrong side.

**Comment by tsujan** [comment]
> All is done except system theme, I've no clue there. Adding an image could result in invisible arrows.

We shouldn't add any image (except for spacers and main menu icon) to the System theme. Once you add an image, Qt stylesheet style will interfere with the Qt widget style (Fusion, Breeze, Kvantum...). The latter is supposed to be used by the System theme.

I'll check the System theme soon.

**Comment by tsujan** [comment]
@stefonarch 
I checked the System theme and didn't find any problem in RTL or LTR menu arrows with Fusion, Breeze and Kvantum widget styles.

**Comment by stefonarch** [comment]
> I checked the System theme and didn't find any problem in RTL or LTR menu arrows with Fusion, Breeze and Kvantum widget styles.

It's then only Oxygen, didn't change the widget styles.

> Feel free to merge the PR if you're satisfied with it.!

I see it's 6 years ago I started that theme... done.

**Comment by tsujan** [comment]
> It's then only Oxygen

Oh, yes, Oxygen has RTL bugs.

**Comment by tsujan** [comment]
Oxygen's RTL bugs in menus:

oxygen

**Pull request merged**
