### PR TITLE
Added arch colors theme

### PR DESCRIPTION
**Pull request by stefonarch**
I'm afraid the *.svg files need some work.

### CODE REVIEW

**Comment by tsujan** [comment]
Oh, I'd forgotten about lxqt-themes. Should test https://github.com/lxqt/lxqt-themes/pull/39, add a PR for another theme and, of course, test this one.

**Review by tsujan — APPROVED** [review]
It's a nice addition.

The only problems I found were these: the plus sign of status notifier (when some items were hidden) and the text of keyboard status indicator got black on moueover and couldn't be seen; also, the text of CPU load wasn't visible.

I suggest a change like the following and then a merge:

```xml
#StatusNotifier QToolButton:hover,
#KbIndicator QToolButton:hover {
   color: white;
}

#LXQtCpuLoad {
    qproperty-fontColor: white;
}
```

**Comment by stefonarch** [comment]
Thanks for testing and finding the issues, I applied some changes now (not white for the + but` #13d4ff` inherent with the theme)
I didn't notice the issue with the kbindicator because I use flags.

**Comment by tsujan** [comment]
> I didn't notice the issue with the kbindicator because I use flags.

Yes, it's hard to test themes completely; I'm not sure about my tests either. IMHO, the most important tests are about switching between light and dark widget styles. This theme passed that test.

**Comment by stefonarch** [comment]
One test failed: compiling.
I had some doubt about folder name with spaces....

**Comment by tsujan** [comment]
> One test failed: compiling.

I saw the space but it worked well when I put it in `~/.local/share/lxqt/themes`. Didn't think about compilation.

**Comment by stefonarch** [comment]
Hm, actually it wasn't compilation and installation, but `debinstall` for making the .deb package.
Anyway, better on the safe side.

**Pull request merged**
