### PR TITLE
Fix selection colors

### PR DESCRIPTION
**Pull request by tsujan**
This is @stefonarch's PR https://github.com/lxqt/lxqt-themes/pull/47 but against the correct source.

### CODE REVIEW

**Comment by stefonarch** [comment]
I didn't touch frost and light which are both heavily based on palette colors.

**Comment by tsujan** [comment]
> not sure for clearlooks, there is no qmenu too and panel menus with dark palette are out of place IMHO, selected background is from widget and text from palette.

I'll check it in a day or two. Hopefully we could fix everything before 1.0.0. If not, we'll do it later and make a point release for lxqt-themes.

**Comment by tsujan** [comment]
Tonight, I found and fixed some problems in Arch-Colors, especially in its lists. Tomorrow, I'll check the other themes.

I didn't squash the commits for them to be distinguished from each other easily. It's better to have separate commits here.

**Comment by tsujan** [comment]
Oh, if you add a commit, please first clone the updated branch. It's easy to miss that.

**Comment by stefonarch** [comment]
> Oh, if you add a commit, please first clone the updated branch. It's easy to miss that.

Will do, but atm  I can't see lxqt-*.qss files anymore ;) 
Thanks for looking through!

**Comment by tsujan** [comment]
There's no rush. And I might have time to check all of them tomorrow.

**Comment by tsujan** [comment]
My reply (https://github.com/lxqt/lxqt-themes/commit/f0f8c44fa3cf62b464c05f967a65ee0013f3280d#commitcomment-59189341) didn't show up here. Weird GitHub problems!

**Comment by tsujan** [comment]
Clearlooks had lots of problems. I fixed the most important ones. I think the rest is tolerable for now.

**Comment by tsujan** [comment]
I'm working on the dark theme now; please skip it.

**Comment by tsujan** [comment]
OK, my work with the dark theme is finished. Only kde-plasma and silver are remained. I haven't checked them yet. Would you do it? If you don't have time, please tell me to check them too.

BTW, except for the Kvantum theme, RTL isn't taken into account by most themes. It isn't a major problem and I think we can ignore it for now.

**Comment by stefonarch** [comment]
The fixes for selection colors I've already done in both:
https://github.com/lxqt/lxqt-themes/pull/48/files#diff-4b195a01bacccd49c0da000319b994016d024de9ab5f6b3a2c656b970ba3de78
https://github.com/lxqt/lxqt-themes/pull/48/files#diff-3f4b263da9867821e34b8a052be21b2b6cb3f8d7beaaa7c6ddd82ad69c7deaff

but a recheck by you would be appreciated :)

**Comment by stefonarch** [comment]
I added desktopswitch style to Leech, I see that it's missing in clearlooks too. I think styling them the same as taskbarbuttons would be better, atm no way to know on which desktop you are.

**Comment by tsujan** [comment]
> but a recheck by you would be appreciated

I'll check them.

> I added desktopswitch style to Leech, I see that it's missing in Clearlooks too.

Will fix it.

> Clearlooks takes palette colors in main menu search results.

That isn't a problem, IMO. Some widgets can be left to the widget style in some themes.

BTW, the "urgent" desktop has a bug in the code (its description takes time, so I skip it). Because of it, I didn't add `#DesktopSwitch QToolButton[urgent="true"]` to the Kvantum theme.

**Comment by stefonarch** [comment]
I've done it in clearlooks now already, together with the desktopswitch (forgot to mention it in the commit message).

I think the search results list isn't a problem in bright themes because hardly one will use a dark palette with those, but is one in Leech with default palette.

**Comment by tsujan** [comment]
> I'll fix silver's results list as next.

Thanks!

**Comment by stefonarch** [comment]
It never stops. 
I found palette's selection colors in "add plugin" dialog, here in kvantum but I think most themes are affected.
schermata-11-03-21-42-01

**Comment by tsujan** [comment]
> I found palette's selection colors in "add plugin" dialog

The "add plugin" dialog isn't a part of CSS. It should use the widget style (except for it menus, if any, which are inherited from CSS, unfortunately).

**Comment by stefonarch** [comment]
I could fix also menu search in Leech tomorrow.

**Comment by tsujan** [comment]
> I could fix also menu search in Leech tomorrow.

OK. I'll check everything after you do it.

I'll write the release Note for LXQt 1.0.0 tomorrow and, probably, start the release procedure the day after it. Will tel you when the Weblate merges should be stopped.

**Comment by tsujan** [comment]
After your last commit, I tested it and added another commit, by making the following changes:

Silver: The main panel of Runner didn't have a bg. I made it like Panel. I fixed its drop-down list and menu separators too, by making them like Panel's. Also, checked indicator was missing from Panel's context menus; I added it.

Leech: Active desktop and active task button weren't clearly visible. I changed their bg by using a theme color and making it lighter.

I think it can be merged now — unless you find another major problem.

**Comment by tsujan** [comment]
Oh, I forgot about kde-plasma theme. It's a total mess. I'm working on it now...

**Comment by stefonarch** [comment]
I wonder why we didn't see any bug reports for themes...
Btw compiled all prerelease branches,  like a charm.

**Comment by tsujan** [comment]
Done, at last! Running away from qss files for a while... ;)

> I wonder why we didn't see any bug reports for themes...

It's simple; they don't do all tests that we do. Also, LXQt can change palette colors only recently. I think most users still don't know about it.

> Btw compiled all prerelease branches, like a charm.

Many thanks!

Mergeing?

**Comment by stefonarch** [comment]
I thought I fixed another small issue in Silver, but it's impossible, clear icon with dark icons  in papirus remain hardly visible.

In kde-plasma I see a colorpicker issue with dark palette, didn't see other issue. Me too: no *.qss files for some time ;)

**Comment by tsujan** [comment]
> but it's impossible,...

Yes, I know about it. It's a Qt bug in its style sheet code. Just ignore it.

> In kde-plasma I see a colorpicker issue with dark palette, didn't see other issue. Me too: no *.qss files for some time ;)

Since we both are traumatized, let's merge this to save our mental health! Agreed?

**Comment by stefonarch** [comment]
Ok, hardly anybody  will use a dark palette with kde-plasma.

**Comment by tsujan** [comment]
Apart from its problem with dark styles in some themes (not only in kde-plasma), colorpicker has a small but general issue. It doesn't adjust its width to its text. It should be fixed in the code but I'm not sure that will be easy (or even possible).

**Pull request merged**
