### PR TITLE
Prerelease changes

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Review by jubalh — APPROVED** [review]

**Comment by stefonarch** [comment]
Found 2 old themes... https://github.com/lxqt/LXQt-graphics/tree/master/themes 
Honestly it's better to let them there :)

**Comment by tsujan** [comment]
@stefonarch 
I don't think libqtxdg will be ready in 2022-04-15. So, you can still make PRs if you want to. If they're merged, I'll update this PR, like what I did in https://github.com/lxqt/pcmanfm-qt/pull/1565.

**Comment by tsujan** [comment]
@stefonarch
I meant separate PRs. This PR is only for changelog and versioning.

**Comment by stefonarch** [comment]
@tsujan Can you add the last commit? https://github.com/lxqt/lxqt-themes/pull/50 can wait IMO.

**Comment by tsujan** [comment]
@stefonarch 
I will, soon

I'll also release LXQt soon, in spite of the current situation of libqtxdg.

**Comment by tsujan** [comment]
Done.

**Pull request merged**
