### PR TITLE
Added palettes for suitable themes

### PR DESCRIPTION
**Pull request by stefonarch**
Related to https://github.com/lxqt/lxqt-themes/pull/50 which could be integrated after.

### CODE REVIEW

**Comment by tsujan** [comment]
The installation path is correct.

There's only a small thing that needs a short story:

Ambiance was inspired by a an old GTK theme with the same name in Ubuntu. It doesn't exist anymore but was a *light* theme.

Kvantum has a light theme called "KvAmbiance" (different from "KvAmbience") which matches it exactly and was made for use under Unity. Since Gnome devs wanted a monopoly on GTK themes, they made theme making harder and harder. So, Ambiance became impossible after a while.

**Comment by stefonarch** [comment]
So what do you mean with this? We shouldn't add a ambiance palette but we have an "ambiance" theme?

**Comment by tsujan** [comment]
No. I just mean Ambiance is a light theme, with the above-mentioned colors. It fits the dark Ambiance LXQt style (→ screenshots of old versions of Ubuntu).

**Comment by stefonarch** [comment]
Ok, thanks,got it now. 
I just took menu (background)colors for window colors.
But as things evolve: we could have "ambiance bright" and "ambiance dark"?

**Comment by tsujan** [comment]
Ambiance had dark menus and light windows. It was a dark-and-light theme.

Qt palettes can't support dark-and-light themes but Qt styles can (as far as I know, only Kvantum does). This is how Ubuntu's Ambiance looked like:

ambiance

**Comment by stefonarch** [comment]
We should finish this here. I was thinking - if doable - about an checkbox "Set also matching color scheme" in themes settings.
https://www.reddit.com/r/LXQt/comments/tb6u6o/dark_theme/

**Comment by tsujan** [comment]
That reddit page is about what the user calls "color profile". Either he has an outdated version of LXQt or he hasn't launched the config dialog — most probably, the first.

**Comment by tsujan** [comment]
There's a merge conflict. Would you fix it?

**Comment by tsujan** [comment]
If it has passed your tests and you don't have a plan to change it, please merge it. We could enhance it later if needed.

Hopefully, I'll remember what minor problem I saw in some Panel themes and fix it.

**Comment by stefonarch** [comment]
Tested on my other PC, some link colors could be improved.

**Pull request merged**
