### PR TITLE
 Added backlight style, silver theme

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
I had a suggestion that has been helpful to me: test an LXQt theme with a light as well as a dark widget style (make sure to restart the panel after changing the style). In that way, a usual mistake may show up: setting the background without setting the foreground, or vice versa. I've made that mistake several times but the above-mentioned double test has revealed it.

The dark margin of the backlight slider becomes a light strip with dark themes. Its cause is `background: palette(text);` inside `#Backlight > SliderDialog > QSlider`. Just remove it:

```css
#Backlight > SliderDialog > QSlider {
    margin: 2px;
    padding: 2px;
}
```

Also, please remove `color: #343839;` from `#MainMenu QLineEdit` because it results in unreadable text with dark widget styles:

```css
#MainMenu QLineEdit {
   border: none;
   margin: 10px;
   padding: 2px 7px 2px 2px;
   border-radius: 3px;
}
```

`color:black;` should also be added to ` VolumePopup  > QPushButton` because its background is set:

```css
VolumePopup  > QPushButton {
   background: #8c8f8f;
   color:black;
   padding: 2px 10px;
   margin: 3px;
   border: none;
   qproperty-iconSize: 20px;
}
```

You may want to change the `width` inside `VolumePopup  > QSlider::groove:vertical {` to `5px`, to make it like the backlight slider, but it's not a mistake:

```css
VolumePopup  > QSlider::groove:vertical {
   background: hsv(0, 0, 9);
   width: 5px;
   border-radius: 3px;
}
```

**Comment by stefonarch** [comment]
Thanks for the hint, my themes were born when palette colors wasn't easily changed. 
Testing with a dark palette I found 2 other issues, one is fixed, the other makes me scratch my head, menu titles:
schermata-08-31-18-35-01

On a sidenote: we have "reset" for the bright palette - having 2 buttons one for a dark one for a bright default could be an enhancement.

**Comment by tsujan** [comment]
> the other makes me scratch my head, menu titles

I could add a commit to this PR later if you have no objection.

> having 2 buttons one for a dark one for a bright default could be an enhancement.

I understand. Maybe later. For now, the reset button changes colors to that of Qt for Linux (= Fusion) and Qt has no dark variant.

**Comment by stefonarch** [comment]
Done and some small other changes too.
I still don't  understand why menu titles follow  `palette(text)` and was not able to override this in `QMenu {}`

**Comment by stefonarch** [comment]
I noticed that https://github.com/lxqt/lxqt-themes/commit/cc214d9eddf992b1fb8408ca05ade43de9d03913 was incomplete and removed `font:14px dejavu` for search field in lxqt-runner.qss

**Pull request merged**
