### PR TITLE
Whitespace cleanup for theme .qss files

### PR DESCRIPTION
**Pull request by ianfarrell47**
Fixes whitespace errors and uses tabs for rules

### CODE REVIEW

**Comment by ianfarrell47** [comment]
The beautifier I used is https://www.freeformatter.com/css-beautifier.html and then I replaced ">" with " > ".

**Comment by ianfarrell47** [comment]
I was not sure if I should use 4 spaces (the previous standard) or tabs (less bytes). Now that I've looked at file sizes I think 4 spaces would be better.

**Comment by stefonarch** [comment]
This _should_ be safe to merge. What do you think @tsujan ?

**Comment by tsujan** [comment]
> What do you think @tsujan ?

I don't like how comments (/*....*/) that were in front their corresponding lines are misplaced by it. For example, search `/*colors affect also`.

Also, it isn't easy to review. One mistake can cause a problem. IMHO, the PR should have been split into separate PRs, each for one theme.

**Comment by stefonarch** [comment]
I agree -- too many files to review - better a PR for each theme.

**Comment by ianfarrell47** [comment]
I will close this and in new ones preserve comment placement.

I see a lot of 3-space and 4-space indentation in the themes. I wonder if leaving that alone is good, or if a standard indentation is desirable.

**Comment by stefonarch** [comment]
I think 4 dots is ok, themes were written by different authors.

**Pull request closed without merging**
