### PR TITLE
Update kde-plasma/lxqt-panel.qss and add overbars

### PR DESCRIPTION
**Pull request by ianfarrell47**
According to the discussion in #57.

- Added overbars to Backlight, Directory Menu, Mount, World Clock
- Added vertical padding to Sensors
- Whitespace cleanup

Currently the `:on` pseudo-state isn't working in Directory Menu and World Clock

### CODE REVIEW

**Comment by stefonarch** [comment]
Thanks, will test it. You forgot Kde→KDE ;)

**Comment by stefonarch** [comment]
> Currently the `:on` pseudo-state isn't working in Directory Menu and World Clock

Here it does work on both. Personally I don't like it much on worldclock.

**Comment by ianfarrell47** [comment]
I'm having issues working with Git and Github. The above commit only moved one file from themes/kde-plasma/ to themes/KDE-Plasma/. Renaming the directory updates the text in lxqt-config-appearance.

**Comment by stefonarch** [comment]
You should have 2 jkde- directories now in your theme folder, just move all files in KDE-plasma, then delete Kde-plasma, followed by
```
git add .
git commit --amend (just close the editor, leave the message unchanged)
```
then push it here.

**Comment by ianfarrell47** [comment]
Currently the only plugins with proper styling for vertical panel orientation are Taskbar and Spacer. Taskbar's widget seems to be automatically rotated - there are no `[orientation="vertical"]` definitions on it. Taskbar uses `[orienttion="vertical"]` and `[orientation="horizontal"]`.
I could add orientation definitions to all the widgets, but Taskbar working automatically suggests a better solution.

**Comment by stefonarch** [comment]
@ianfarrell47 rebasing is needed.

**Comment by ianfarrell47** [comment]
Sorry for the delay. I was attempting to learn how to rebase, but I still do not know how.

**Comment by stefonarch** [comment]
It's not my peace of cake too. The easiest way is start again IMHO
* copy `lxqt-panel.qss` to some location out of the repo
* `git checkout master`, pull the last changes and delete the branch ` git branch -D kde-plasma-overbars`
*` git checkout -b kde-plasma-overbars`
* copy back the modified qss file  and rename kde-plasma directory
*` git add . && git commit `
* `git push --force`

**Comment by stefonarch** [comment]
@ianfarrell47 If you don't mind I could make a PR with your changes - it would be nice to have it in 1.1.0

**Comment by ianfarrell47** [comment]
@stefonarch Yes, please.

There are some issues still:
- System Clock and its overbar are shifted down a bit
- I made sure each plugin has a 3px space between the next one, but cheated by using `margin-right: 0px;`
- `:on` state still isn't working on my install.
- Plugins on vertical panels should be like TaskBar and have the "overbar" on side.

**Comment by stefonarch** [comment]
Done in https://github.com/lxqt/lxqt-themes/pull/68, please recheck @ianfarrell47 
Only changes to your PR:
* removed state:on where it cannot work (it's only in desktopswitch and taskbar buttons where something is active)
* fixed worldclock overbar

**Pull request closed without merging**
