### PR TITLE
Added missing arrows for RTL

### PR DESCRIPTION
**Pull request by stefonarch**
First draft, have to recheck it.

### CODE REVIEW

**Comment by stefonarch** [comment]
There is an issue with Frost theme and dark palette: arrow invisible. Frost was thought to use light palette colors to be a dark theme.

**Comment by stefonarch** [comment]
It was  not only left arrow of the dark theme... I just flipped the objects but didn't move them to the left too.

**Comment by tsujan** [comment]
> I just flipped the objects but didn't move them to the left too.

Since the arrows are small, it isn't important, but I'll check the SVG images (of this PR).

**Comment by stefonarch** [comment]
In dark theme it was clearly visible;
schermata-8 apr 15:41

**Comment by tsujan** [comment]
I haven't checked the images yet, but if you mean that menu arrows can be hardly visible with Frost, yes, that's possible. It depends on the active widget style and its palette. If it has a light window color and a dark selection color, Frost's menus will have a dark background while its selected items will have a light background; and conversely. Therefore, there's always a widget style that makes Frost's menu arrows hardly visible.

Since Frost's colors change with the active widget style, we can choose an arrow color that is "reasonably" visible against both dark and light backgrounds. A color with a value around 127 is good, like `#7f7f7f`.

**Comment by stefonarch** [comment]
It's already light grey, but in my case (Valendas palette) it doesn't solve because of `background-color: palette(text);` for QMenus. Main menu icon is also hardly visible now and with white text in some dark palette it's invisible . IMO we can't do nothing about it.

 If we implement a system (checkbox) to change palette together with theme it has to be the default palette for frost.

**Comment by tsujan** [comment]
> it doesn't solve because of background-color: palette(text);

That's a logical problem of using `palette(x)` in stylesheets: you can't predict the palette. If you use it, you should do it cautiously to guarantee visible texts, but you couldn't guarantee clearly visible images (for menu arrows or other elements).

However, there are colors that are visible against usual dark and light backgrounds.

**Comment by tsujan** [comment]
Also, images like the attached one are visible against most backgrounds. You may want to heck it.

[right.svg.zip](https://github.com/lxqt/lxqt-themes/files/8455256/right.svg.zip)

**Comment by stefonarch** [comment]
That's a good idea, bi-color!

**Comment by stefonarch** [comment]
I tested it, works with all palettes, should we use it in Frost?

**Comment by tsujan** [comment]
> I tested it, works with all palettes, should we use it in Frost?

If you find it good, why not?

**Comment by tsujan** [comment]
Feel free to merge it if you're satisfied with the result.

BTW, a few newlines are still missing, although that isn't important.

**Comment by stefonarch** [comment]
Actual Frost arrow, following your idea:
schermata-10 apr 14:52

Learnt something about SVG, thanks!

**Comment by tsujan** [comment]
> Actual Frost arrow, following your idea:

Yes, that's another possibility. Previously, I used something like it in an icon set but in black and white and with translucency (attached).

[right.svg.zip](https://github.com/lxqt/lxqt-themes/files/8459125/right.svg.zip)

**Pull request merged**
