### PR TITLE
Some fixes for overbars and correct naming.

### PR DESCRIPTION
**Pull request by stefonarch**
Replaces https://github.com/lxqt/lxqt-themes/pull/66-  thanks!
Fixes https://github.com/lxqt/lxqt-themes/issues/57

### CODE REVIEW

**Comment by ianfarrell47** [comment]
Works great. The `margin: 3px; margin-right: 0px;` causes problems in some cases - left and right margins should be the same. `margin: 3px 1.5px 3px 1.5px;` might not work, because of the decimal.

**Comment by tsujan** [comment]
> .. might not work, because of the decimal.

No, margins should be integers.

**Comment by stefonarch** [comment]
@ianfarrell47 made the margins equal (better for RTL desktops). Do you see still issues?

**Comment by ianfarrell47** [comment]
Works good, only issue I saw was the overbar being too small horizontally over World Clock
screenshot
.

**Comment by stefonarch** [comment]
I don't see it as an issue, compared with desktopswitch:
schermata-15 apr 08:38-01
schermata-15 apr 08:38

Personally I don't see the point of having an overbar in worldclock, as it will be used only for opening the calender or timezones with  middleclick.

**Comment by ianfarrell47** [comment]
Horizontal margins are a bit inconsistent but the .qss file is good from what I can tell. I added the bar to World Clock because Plasma has one, afaik.

**Comment by stefonarch** [comment]
It's preferable to preserve original authors ideas as far as possible, yes.

**Pull request merged**
