### PR TITLE
Fixed/improved quicklaunch placeholder styling

### PR DESCRIPTION
**Pull request by stefonarch**
With a panel size of >35 it's perfect now, but also below it's at least readable.

### CODE REVIEW

**Comment by tsujan** [comment]
Merge it if it has passed your tests. The changes seem OK.

**Comment by tsujan** [comment]
BTW, somewhere I wrote about a problem in some themes, that I wanted to fix. Later, I found out that it was an issue in Qt's stylesheet. Nothing can be done for it; any workaround would damage other places.

The problem is in Taskbar's right click menu → "To Desktop" sub-menu. The horizontal space that's given to that sub-menu is less than that of normal menus. The sub-menu is OK without stylesheet (with system theme) though. I think we have to tolerate it.

**Comment by stefonarch** [comment]
I still think we should fix the system theme's taskbar. It's not usable with Breeze|qtcurve|Oxygen widget styles - I can't see any reason for limiting it to fusion or windows,

**Comment by stefonarch** [comment]
Hm, maybe you were right, I can't find a good way, adding `border: 1px solid transparent;` to QtoolButtons works for the text but kills the widget style.

**Comment by tsujan** [comment]
> I still think we should fix the system theme's taskbar. It's not usable with Breeze|qtcurve|Oxygen widget styles

The System theme is supposed to not interfere with the widget style. Years ago, I found out that Breeze's problem is because of a bug in Breeze. I can't find my old comment now but I assure you that KDE's styles have a common bug in how they draw tool-button texts.

The user can work around Breeze's problem by using an icon-only taskbar with the System theme.

**Comment by tsujan** [comment]
Found it: https://github.com/lxqt/lxqt/issues/1525#issuecomment-406907067

A KDE dev's denial: https://bugs.kde.org/show_bug.cgi?id=397337#c1. They closed the report after giving it a "NEEDSINFO" tag, as if there can be a more specific info than pinpointing the buggy lines of code.

**Comment by stefonarch** [comment]
Yeah, Oxygen has the same issue...

**Pull request merged**
