### PR TITLE
Adding kde-plasma-refresh

### PR DESCRIPTION
**Pull request by iamthesenate1**
***[Disclaimer] This is very much a draft, and many things **will** change. Please don't consider this a final "version".*** 

First of all, I know themes are very subjective . Maybe some of these changes will never see the light of upstream, but some of them are, IMO, logical. For example removing  the border of the menu:
screen02 ->Here is the before, where the menu has a very ugly border.
screen03
-> Here is the after,  without the  menu border.
 
Other changes (planned or done) include:
- [x] Making the panel semi-transparent.
- [x] Making the menu semi-transparent. -> I really don't know if it is a good idea. To me it just looks uglier.
- [ ] Other improvements.

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks for paying attention to details!

> but some of them are, IMO, logical. For example removing the border of the menu

Actually, the inverse is logical. The border is needed when the background has the same color, exactly like the a part of your second screenshot, in which the menu can't be distinguished from its background because you've removed its border..

One word about SVG images:

I saw the same thing in https://github.com/lxqt/lxqt.github.io/pull/69#issuecomment-872471993 too: SVG files need to be cleaned up before being used. There are various tools for that, SVG Cleaner being one of them. For example, your `themes/kde-plasma-refresh/left-arrow.svg` has many redundant lines that add to its size unnecessarily.

**Comment by tsujan** [comment]
BTW, you don't need to be root to work on themes (your screenshots suggest that you edit themes as root). Optionally and more comfortably, you could use the directory `~/.local//share/lxqt/themes/`.

**Comment by iamthesenate1** [comment]
Thanks for your feedback. I really appreciate it. 

> Actually, the inverse is logical. The border is needed when the background has the same color, exactly like the a part of your second screenshot, in which the menu can't be distinguished from its background because you've removed its border.

I see your point. Still. I find the borderless version more modern. I know this is very subjective. Maybe a border of another color? (Maybe the blue that is used for the selected item?). I'll keep investigating other options.

> One word about SVG images:
> 
> I saw the same thing in lxqt/lxqt.github.io#69 too: SVG files need to be cleaned up before being used. There are various tools for that, SVG Cleaner being one of them. For example, your themes/kde-plasma-refresh/left-arrow.svg has many redundant lines that add to its size unnecessarily.

I didn't know about SVG Cleaner. Thanks so much for pointing it out. I was actually wandering if there was something to make SVG file sizes smaller.

**Comment by iamthesenate1** [comment]
> BTW, you don't need to be root to work on themes (your screenshots suggest that you edit themes as root). Optionally and more comfortably, you could use the directory `~/.local/share/lxqt/themes/`.

Thanks.

**Comment by tsujan** [comment]
> I was actually wandering if there was something to make SVG file sizes smaller.

For example, with correct settings in SVG Cleaner (or another tool), `themes/kde-plasma-refresh/left-arrow.svg` can be reduced to this without losing anything:

```xml
<svg width="22" version="1.1" xmlns="http://www.w3.org/2000/svg" height="22" viewBox="0 0 22 22">
<g transform="translate(0,-1030.3622)">
<path style="fill:#4d4d4d" d="m 15,1049.3622 .707,-.707 -6.125,-6.125 -1.168,-1.168 1.168,-1.168 6.125,-6.125 -.707,-.707 -6.125,6.125 -1.875,1.875 1.875,1.875 6.125,6.125 z "/>
</g>
</svg>
```

In that way, 7KB becomes 335B.

**Comment by tsujan** [comment]
> I know this is very subjective.

Yes, it is :) What you find ugly may be elegant to another person, and vice versa. Tastes can differ very much!

That's why it's better to focus on practical matters only, IMHO.

**Comment by iamthesenate1** [comment]
> In that way, 7KB becomes 335B.
> 
> EDIT: I made it even simpler, with a size of 224B.

WOW. 
I have no words. The only thing I can say is: "ipse se nihil scire id unum sciat.". 

I'll start updating all SVG's from my PR's ASAP.

**Comment by iamthesenate1** [comment]
> > I know this is very subjective.
> 
> Yes, it is :) What you find ugly may be elegant to another person, and vice versa. Tastes can differ very much!
> 
> That's why it's better to focus on practical matters only, IMHO.

I know... . I think I have found a compromise. The border still remains, but it is now blue and at 30% transparency. The border is now less obvious,  but still enough to differentiate the background from the menu.
screen04

**Comment by iamthesenate1** [comment]
Hi. While experimenting with different settings I might have discovered a bug. Basically, every next result doesn't get applied custom opacity: 
screen05
Am I doing something wrong or is a bug.

**Comment by tsujan** [comment]
With every change or set of changes, you should restart the panel (from LXQt session settings) to see the *real* difference. Things like translucency can't be applied on the fly. There's no bug on our part.

Also, you need compositing with translucency.

**Comment by iamthesenate1** [comment]
> With every change or set of changes, you should restart the panel or lxqt-runner (from LXQt session settings) to see the real difference. Things like translucency can't be applied on the fly.

I know, I've been doing this every time I changed something, so this is not the cause.

> Also, you need compositing with translucency.

I have KwinFT so this is not the problem either,

**Comment by tsujan** [comment]
Then, sorry, I should have misunderstood the problem you were referring to — especially the meaning of this sentence wasn't clear: "every next result doesn't get applied custom opacity". Please describe it in a step by step way.

**Comment by iamthesenate1** [comment]
Nvm. It was my mistake. The plasma theme has the results of lxqt-runner show different colors for consecutive results. Initially, I didn't realise this was happening and when I applied the translucency I thought there was a bug. Sorry for alarming you.

Here is an exemplification:

1.A lighter shade of white
2.A darker shade
1.A lighter shade
2.A darker shade
1.A lighter shade
2.A darker shade
...

**Comment by iamthesenate1** [comment]
Also, do you know how to change the darker shade's translucency?

**Comment by tsujan** [comment]
> Also, do you know how to change the darker shade's translucency?

I don't understand what you mean by "darker shade's translucency." For example, an opacity of 80% can be defined as rgba(X, Y, Z, 80%).

**Comment by iamthesenate1** [comment]
> > Also, do you know how to change the darker shade's translucency?
> 
> I don't understand what you mean by "darker shade's translucency." For example, an opacity of 80% can be defined as rgba(X, Y, Z, 80%).

Firs of all, I was mistaken. The lighter shade is the "problem".

> For example, an opacity of 80% can be defined as rgba(X, Y, Z, 80%).

I know. the problem is the the lighter shade(again. sorry for my mistake)(see https://user-images.githubusercontent.com/77978836/124358853-da0db280-dc2a-11eb-9677-a81866722963.jpg), is not affected by the rgba setting.

**Comment by tsujan** [comment]
Sorry, I don't know what you mean by "darker/higher shade translucency".

Opacity has its separate value. If you have a color gradient, you could give separate opacity values to its "stop" colors and they will be exactly as you put them there. That's related to CSS, not Qt.

**Comment by iamthesenate1** [comment]
This: 
screen65

**Comment by tsujan** [comment]
You may want to be much more specific when asking questions ;) Your attached screenshot didn't explain anything. Or perhaps another LXQt member could understand your question.

**Comment by iamthesenate1** [comment]
Well, the first and the third result are still solid white, without the translucency applied.

**Comment by iamthesenate1** [comment]
> <property name="alternatingRowColors">
>       <bool>true</bool>
>      </property>

This is the relevant part in dialog.ui (from lxqt-runner)

**Comment by tsujan** [comment]
This is LXQt Runner popup with translucency (I made it in a few minutes -- didn't care about elegance):

translucency

The relevant parts of CSS:

```css
Dialog {
    background-color: transparent;
}

#commandList {
    background-color: rgba(0, 0, 0, 30%);
    alternate-background-color: rgba(0, 0, 0, 10%);
    color: white;
    selection-color: black;
}

#commandList::item:selected {
    background: rgba(255, 255, 255, 50%);
}

#commandList::item:hover {
    background: rgba(255, 255, 255, 25%);
}

#commandList::item:selected:hover {
    background: white;
}

#commandList::item:alternate:hover {
    background: rgba(255, 255, 255, 12%);
}
```

You should have made a mistake somewhere.

**Comment by iamthesenate1** [comment]
>     alternate-background-color: rgba(0, 0, 0, 10%);

This is the line I was missing. Thanks and sorry for not being able to explain it better.

**Comment by tsujan** [comment]
Oh, now everything is clear. By "darker shade" you meant *the alternate background color*. It isn't necessarily darker; depends on the theme.

Please note that the above CSS isn't good at all -- I made it just to show that there was no problem. You should give `alternate-background-color` a color *different from* `background-color` if you want it to be distinguished against all backgrounds with translucency.

**Comment by iamthesenate1** [comment]
> Oh, now everything is clear. By "darker shade" you meant the alternate background color. It isn't necessarily darker; depends on the theme.

Yes. I didn't know how it was named so I tried to explain from what I saw in the current plasma theme.

> You should give alternate-background-color a color different from background-color if you want it to be distinguished against all backgrounds with translucency.

I know. This is the weird part. I am working on top of the current plasma theme and, while that line was missing, the alternate color still existed,.

**Comment by tsujan** [comment]
CSS can be complex. A definition may be missed by the theme maker while it affects everything.

BTW, you may already know it but to be completely clear:

LXQt doesn't have "Plasma". "KDE-plasma" was just a name given to a certain theme. LXQt uses QSS (Qt's CSS implementation) for its panel, runner and some other components, while KDE uses Qt Quick and has its own definitions. We avoid Qt Quick in LXQt.

**Comment by iamthesenate1** [comment]
> BTW, you may already know it but to be completely clear:
> 
> LXQt doesn't have "Plasma". "KDE-plasma" was just a name given to a certain theme. LXQt uses QSS (Qt's CSS implementation) for its panel, runner and some other components, while KDE uses Qt Quick and has its own definitions. We avoid Qt Quick in LXQt.

Yes. I know. I used "plasma" as a way to shorten the name.

**Comment by iamthesenate1** [comment]
This is not finalized yet, but I was wandering that if the final changes could be integrated in the current kde-plasma theme. I'm asking because I don't plan for "big" changes, in the sense that, the changes I'll do are not about making something new, but much rather about "refineing". 
Thoughts?

**Comment by tsujan** [comment]
IMO, we'd better not change the looks and feels of the current themes. You made this theme based on your taste; so, it could be reviewed and added as a new theme. Its name already tells that its a variant of kde-plasma theme.

BTW:
 1. There are still non-optimized SVG files.
 2. GitHub isn't happy about the lack of an empty new line in some cases — e.g. in themes/kde-plasma-refresh/application-menu.svg. Please add them. (You could also use a text editor that has an option for adding them automatically — like FeatherPad).

**Comment by iamthesenate1** [comment]
> IMO, we'd better not change the looks and feels of the current themes. You made this theme based on your taste; so, it could be reviewed and added as a new theme. Its name already tells that it's a variant of kde-plasma theme.
> 
> BTW:
> 
>     1. There are still non-optimized SVG files.
> 
>     2. GitHub isn't happy about the lack of an empty new line in some cases — e.g. in themes/kde-plasma-refresh/application-menu.svg. Please add them. (You could also use a text editor that has an option for adding them automatically — like FeatherPad).

Done.

**Comment by iamthesenate1** [comment]
Closing this for now as I don't plan to work on it soon.

**Pull request closed without merging**
