### PR TITLE
Kvantum LXQt theme

### PR DESCRIPTION
**Pull request by tsujan**
An LXQt theme similar to the default Kvantum theme (as far as Qt stylesheet allows).

### CODE REVIEW

**Comment by tsujan** [comment]
A screenshot:

screenshot

**Comment by luis-pereira** [comment]
Cool. I like it. Using it.

**Comment by tsujan** [comment]
@luis-pereira 
Thanks for testing it!

Will wait a few days to see if it can be made more similar to Kvantum's default theme, although I don't think that's possible with stylesheets.

**Comment by AzumaHazuki** [comment]
Oooh, pretty :) This is really classy-looking.

**Comment by tsujan** [comment]
@AzumaHazuki, thanks for testing.

I think this is the most that can be done for imitating `QStyle` by using Qt's stylesheets. Merging....

**Comment by tsujan** [comment]
Oops! A newline is missing. Will remove the file in a PR.

**Pull request merged**
