### PR TITLE
Adwaita and Adwaita-Dark LXQt Themes

### PR DESCRIPTION
**Pull request by AzumaHazuki**
I think these are read to ship. They're the first themes with the Leave dialog styled, and the first with a complete set of theming directives for the Wing Menu...which is _incredibly complicated_, let me tell you!

Making draft PR because I'm sure something here or there was overlooked! Screenshots below:

Adwaita-LXQt
Adwaita-LXQt-Dark

### CODE REVIEW

**Comment by stefonarch** [comment]
Nice work! 
Had a first fast look at it. Are the white tooltips on the Adwaita-darktheme intended? And there is some `.save` file left over.

**Comment by AzumaHazuki** [comment]
> Nice work! Had a first fast look at it. Are the white tooltips on the Adwaita-darktheme intended? And there is some `.save` file left over.

Sorry about the .save! Nano does that by its own, feel free to delete it. As to white tooltips, do you mean the light-yellow boxes that are showing over my terminal emulator? If so, yes, though if the popups are different colors in the original themes i can go change them.

**Comment by stefonarch** [comment]
I meant the tooltips in lxqt-panel, I don't see any styling for them. Example from my Valendas theme:
```
QToolTip {
   border: 0px solid #4C4C4C;
   background:rgba(50, 50, 50, 60%);
   color: #dce7f5;
   padding: 2px;
   margin: 0px;
   border: 1px solid white;
   border-radius: 5px;
}
```

**Comment by AzumaHazuki** [comment]
Sorry for the late reply! Work has been nuts (retail pharmacy in a decent-sized US city...). If I change the files in my repo, does it require to make another PR afterwards?

**Comment by stefonarch** [comment]
> If I change the files in my repo, does it require to make another PR afterwards?

No, just push to your master it will be here.

**Comment by AzumaHazuki** [comment]
Okay, they're ready :) I've noticed even in Xfce the light Adwaita theme has black tooltips with white background text, which seems a little weird. Also did a little tweaking to the logout buttons on the Leave dialog so they're a bit friendlier-looking. Thank you for taking so much time with me on this!

**Comment by stefonarch** [comment]
Another quick look now: 
The calendar pop up is styled by my palette and not by `lxqt-panel.qss`. 
It's not an issue when a bright palette is used on adwaita, but on adwaita-dark this looks bad. You could add also a palette for it.

**Comment by AzumaHazuki** [comment]
That took a while, but I think I got the calendar widgets styles :) Also uploaded the respective palette files. QSS doesn't seem to let one change the red color of weekend days nor the shape of the highlighted day selection color swatch (it's always a rectangle) so this isn't accurate to the Xfce calendar, for example, but it looks good.

**Comment by AzumaHazuki** [comment]
This weekend I did a complete refactor of Clearlooks, and also made a separate repository of <a href=https://github.com/AzumaHazuki/lxqt-themes-devuan>Devuan-style respins</a> based on said refactoring. There is much more coverage and polish now, including WingMenu and Leave dialog theming.

**Comment by AzumaHazuki** [comment]
Have completely redone the Leech theme, including some scrollbars and handles mimicking the GTK2 theme I'm inordinately proud of =P How is the review coming?

LXQt-Leech

**Comment by stefonarch** [comment]
Please don't mix to much stuff in one PR i't's one subject, this here is only about adwaita, review with too many files is impossible. 

Please make separate PRs, one for each other theme.

**Comment by AzumaHazuki** [comment]
How do I do that? It looks like only 1 PR can be open at once and it tracks every single change made...

**Comment by stefonarch** [comment]
> How do I do that? It looks like only 1 PR can be open at once and it tracks every single change made...

You need to make a branch in your repo but probably you better wait for a new PR until this is reviewed and eventually merged, it's easy to include wrong stuff.

```

git checkout -b <my_theme_changes>
< make changes>
git add .
git commit 
git push
```
For now just remove everything that has nothing to do with adwaita.

**Pull request closed without merging**
