### PR TITLE
Consistent preview images for themes

### PR DESCRIPTION
**Pull request by ianfarrell47**
Preview images were updated and made consistent for the current 12 themes.

Layout is as follows:
- Application Menu (default)
- Spacer (dotted)
- Desktop Switcher (2 desktops)

Images dimensions are 100px * 32px.

### CODE REVIEW

**Comment by stefonarch** [comment]
Nice, thanks. 
GTM

**Comment by tsujan** [comment]
I also think this can be merged.

**Comment by stefonarch** [comment]
@ianfarrell47  It's ready now?

**Comment by ianfarrell47** [comment]
Yeah, all good now.

**Pull request merged**
