### PR TITLE
'Kvantum' .qss whitespace clean-up

### PR DESCRIPTION
**Pull request by ianfarrell47**

### CODE REVIEW

**Comment by ianfarrell47** [comment]
@tsjuan How do we ensure other themes correctly work with Styling/Custom styling, under Configure panel? Everything about this theme is wonderful.

**Comment by tsujan** [comment]
> How do we ensure other themes correctly work with Styling/Custom styling, under Configure panel?

Good question. They can't be compatible.

"Custom Styling" overrides the current QSS. So, it can easily break the current style of the panel. It's rather for the "System" style, which has a minimal QSS and leaves most of the styling to the active widget style (= Fusion, Breeze, QtCurve, Kvantum...).

@stefonarch 
Can we review @ianfarrell47's PRs before 1.2.0 and make sure that no regression is introduced by them? I might start to make "pre-release" PRs next week.

**Comment by stefonarch** [comment]
>  Can we review @ianfarrell47's PRs before 1.2.0 and make sure that no regression is introduced by them? I might start to make "pre-release" PRs next week.

I merged some, but looked only at the syntax, real testing is hard. 

> I might start to make "pre-release" PRs next week.

Nice, I hope for  @slidinghotdog making the PR for  the wing menu in time. I've not much spare time the next 2 weeks unfortunately.

**Comment by tsujan** [comment]
> but looked only at the syntax

If no line has been changed (by mistake), that's enough. But checking every line will take time.

> I hope for @slidinghotdog making the PR for the wing menu in time.

Sadly, even if a PR is made today, I won't have time for reviewing it before 1.2.0.

**Comment by ianfarrell47** [comment]
> "Custom Styling" overrides the current QSS. So, it can easily break the current style of the panel. It's rather for the "System" style, which has a minimal QSS and leaves most of the styling to the active widget style (= Fusion, Breeze, QtCurve, Kvantum...).

All 12 themes support Font color and Background color under 'Configure Panel'. Under 'LXQt Appearance Configuration' there is 'LXQt Theme' which really is only the panel theme if I am not mistaken. Perchance the settings in the right-click configuration of the menu could be moved there whilst the 'LXQt Theme' tr is changed to 'Panel Theme'?

**Comment by tsujan** [comment]
> ... 'LXQt Theme' which really is only the panel theme...

Not true. An LXQt Theme is for all LXQt components that accept style-sheets in their codes: Panel, Runner and notifications. Moreover, it can include wallpapers.

**Comment by ianfarrell47** [comment]
Okay, I think the work is near completion for the .qss files. I keep forgetting about Runner. I know some C++ so I'll peek in the code. Again, and to be more clear, the Start menu items are not taking upon the font color, but again that's minutiae.

**Comment by stefonarch** [comment]
Should be ok all.

**Pull request merged**
