### PR TITLE
Added silver theme

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Not sure what happened here with git submodule, couldn't use my repo as there is a  different lxqt-themes repo.

**Comment by tsujan** [comment]
Would you mind if I cleaned up its SVG files later (without changing their images) and add commits here?

**Comment by stefonarch** [comment]
> Would you mind if I cleaned up its SVG files later (without changing their images) and add commits here?

Not at all, .svg , I've no practice at all with those.

**Comment by tsujan** [comment]
Done.

**Comment by stefonarch** [comment]
Thanks!

**Comment by tsujan** [comment]
It's good but, since its name is "Silver", wouldn't it be better with a silver-like gradient for the panel and without a dark background? Also, I think it would still look better without a background for normal buttons (neither pressed nor hovered).

But I don't want to impose my taste. It's also good as it is.

**Comment by stefonarch** [comment]
I started this years ago, and using it the last months I fixed some details (worlclock timezones on middle click and else), I'd like not to touch it, but if you like to improve it to more _silver_ just go ;)

The name could be changed I agree, I called it also silver-metal but that's not as it is too.

**Comment by tsujan** [comment]
> but if you like to improve it to more silver just go

No. I don't mistake my taste for improvement. It's your theme and it should be as you like it.

Ship it.

**Comment by stefonarch** [comment]
Will think about a better name some time.

**Comment by stefonarch** [comment]
> Will think about a better name some time.

with no results...

**Pull request merged**
