### PR TITLE
replace symlink

### PR DESCRIPTION
**Pull request by stefonarch**
Needs https://github.com/lxqt/liblxqt/pull/303

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Haven't tried it but looks GTM.

**Comment by stefonarch** [comment]
Just realized that the relative path in `wallpaper.cfg` is not backwards compatible because it needs https://github.com/lxqt/liblxqt/pull/303

**Comment by tsujan** [comment]
> Just realized that the relative path in wallpaper.cfg is not backwards compatible because it needs https://github.com/lxqt/liblxqt/pull/303

No change in git needs to be backward compatible. Git needs git.

**Comment by tsujan** [comment]
> lxqt-themes didn't have a version until now.

No, because it has no binary. The version is determined by the release.

**Comment by stefonarch** [comment]
Just mention it in the changelog then?

**Comment by tsujan** [comment]
I'll definitely add it to the changelog when releasing 1.1.0. Making changelogs is an important part of the process, and it's easy: go to the last release, click the "commits" link, and add the descriptions of non-translation commits.

**Comment by stefonarch** [comment]
```
# Minimum Versions
set(C_MINIMUM_VERSION "0.10.0")
```

Before the change themes could be compiled against all versions, so this needs a some change?

**Comment by tsujan** [comment]
Actually I did change it ;) `lxqt-build-tools` doesn't follow LXQt's versioning. We might want to change that (I thought we already did).

**Comment by tsujan** [comment]
In short, there is no problem here. Like any other repository, everything will be OK at the time of releasing — unless I make a mistake, but I haven't so far ;)

**Comment by stefonarch** [comment]
I had in mind if somebody will try to  compile themes on an older version, probably a rare case.

**Comment by tsujan** [comment]
In general, people shouldn't compile git against the latest stable version — unless they know what they're doing. Sometimes they get no error but the result has problems; that's expected.

**Pull request merged**
