### PR TITLE
Style tooltips also in configuration center based on theme

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Tooltips from `panel.qss`

**Comment by stefonarch** [comment]
Using the tooltips style from panel theme has one big issue: if not the palette for the theme is used it can look really weird. To make sure always palette colors are used now, except for light, plasma and clearlooks where the panel tooltip style is still used.
Added a small rounding, and maybe we could use palette also for those 3, as it includes a small rounding of corners.

**Comment by tsujan** [comment]
They are OK — their stylesheets are fine, and the rest is a matter of taste — but please remove them from the System theme, because it's supposed to follow the widget style. Also, since corners are rounded, one pixel can be added to all paddings, but, as I said, it's a matter of taste.

That being said, there is a situation that shouldn't be ignored:

Some users may use LXQt without compositing under X11, in which case, they might see black spots at the corners. Considering that the motivation for this might have been giving nice round corners to tooltips, I'm not sure that we should do it.

**Comment by stefonarch** [comment]
> please remove them from the System theme, because it's supposed to follow the widget style.

We use palette colors  for the panel and its buttons, I don't see why not using palette for tooltips too, especially if users use a dark palette with the system theme which is quite frequent.

>Some users may use LXQt without compositing under X11, in which case, they might see black spots at the corners. 

That is a point, will check how it looks.

**Comment by stefonarch** [comment]
Made a tour on X11 without compositors with xfwm4 and openbox: no issue - corners are rounded  (as they are also for some buttons in the panel in some themes).

**Comment by tsujan** [comment]
> ... I don't see why not using palette for tooltips too...

A widget style like Kvantum can draw tooltips very differently, by using complex SVG images.

> Made a tour on X11

I said that without testing. Now I tested with compositing (under labwc) and found out that I'd overestimated Fusion ;) Fusion and most other styles create only an illusion of corner rounding. That can be clearly seen with an increased radius:

fusion

In contrast, Kvantum results in real corner rounding:

kvantum

**Comment by stefonarch** [comment]
True, but can only be seen with quite zoom:
immagine

**Comment by tsujan** [comment]
Since there's no dark spot and the radii are small, I don't think that's a real problem. IMO, it can be merged after removing it from the System theme.

**Review by tsujan — APPROVED** [review]
GTM

**Comment by stefonarch** [comment]
Done.

**Pull request merged**
