### PR TITLE
First batch new wallpapers

### PR DESCRIPTION
**Pull request by stefonarch**
Some are reworks from existing ones, with and without branding, the photos are from me.

### CODE REVIEW

**Comment by tsujan** [comment]
Very nice, especially photos.

Just a 16:9 version of `waves-logo.png` may be worth adding.

**Comment by tsujan** [comment]
BTW, some `wallpaper.cfg` files don't have empty end lines.

**Comment by stefonarch** [comment]
> BTW, some `wallpaper.cfg` files don't have empty end lines.

I noticed it, featherpad should have added them automatically and rechecking locally I had them. I'll fix them with the final commit.

> Just a 16:9 version of `waves-logo.png` may be worth adding.

Or ship it only 16:9 ?

**Comment by tsujan** [comment]
> featherpad should have added them automatically

Yes, it does by default.

> Or ship it only 16:9 ?

Whatever your see fit. It was just a suggestion. GTM.

**Pull request merged**
