### PR TITLE
 Added backlight-plugin style, frost theme

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
Frost is a special theme: it inverts the colors of the active widget style. So, I think it's better to only use Qt palette colors in it; otherwise, some widgets will become either ugly or unreadable with some widget styles.

Therefore, some `QSlider` colors need to be changed, for both VolumePopup and Backlight.

For VolumePopup:

```css
VolumePopup  > QSlider::groove:vertical {
    background: palette(window);
    width: 5px;
    border-radius: 3px;
}

VolumePopup  > QSlider::handle:vertical {
    height: 10px;
    background: palette(highlight);
    border-radius: 2px;
    margin: 0 -4px; /* expand outside the groove */
 }
...
...
VolumePopup  > QSlider::sub-page:vertical {
    background: palette(window);
    border: 1px solid palette(text);
    border-radius: 3px;
}
```

For Backlight:

```css

#Backlight > SliderDialog > QSlider::groove:vertical {
    background: palette(window);
    width: 5px;
    border-radius: 3px;
}

#Backlight > SliderDialog > QSlider::handle:vertical {
    height: 10px;
    background: palette(highlight);
    border-radius: 2px;
    margin: 0 -4px; /* expand outside the groove */
}
...
...
#Backlight > SliderDialog > QSlider::sub-page:vertical {
    background: palette(window);
    border: 1px solid palette(text);
    border-radius: 3px;
}
```

I also changed `width` in `VolumePopup  > QSlider::groove:vertical` to make it like what you chose in `#Backlight > SliderDialog > QSlider::groove:vertical`.

There are also other places that palette colors aren't used but I think we can ignore them in the current PR.

**Comment by tsujan** [comment]
Having take a look at other parts of Frost, I think it needs more attention. But, again, this PR isn't about them. After this is merged, I might make a PR for Frost.

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
Any reason why this isn't merged?

**Comment by stefonarch** [comment]
Didn't notice your approval...

**Comment by tsujan** [comment]
> too many things going on

For me too; decided to have some rest.

**Pull request merged**
