### PR TITLE
Common wallpapers directory for themes

### PR DESCRIPTION
**Pull request by stefonarch**
Better handling for wallpapers, preparing for
* modify and add missing wallpapers (every theme should have its own)
*  eventually add more wallpapers to choose from

Changing existing wallpapers from desktop configuration will be easier.
Eventually use `/usr/share/wallpapers/lxqt/` instead?

### CODE REVIEW

**Comment by stefonarch** [comment]
Any objections merging this?

**Comment by palinek** [comment]
These design things are out of my radar ... no objections from my side.

**Comment by tsujan** [comment]
This is a good idea. Merge it.

**Comment by tsujan** [comment]
> Eventually use /usr/share/wallpapers/lxqt/ instead?

IMO, no.

**Comment by tsujan** [comment]
Oh, there seem to be a small problem. Is `LXQT_SHARE_DIR` always `/usr/share`? If t isn't, the symlinks will be broken and another way will be needed.

**Comment by stefonarch** [comment]
Good point - will change them.

**Comment by stefonarch** [comment]
For some reason symlinks will be broken:

```
$ file /usr/share/lxqt/themes/dark/triangles.png 
triangles.png: broken symbolic link to ../../triangles.png
 $ ls -l  /usr/share/lxqt/themes/dark/triangles.png 
lrwxrwxrwx 1 root root 19  5 feb 08.56 triangles.png -> ../../triangles.png  

```
Just yesterday I wasn't so convinced anymore about this, because users want to change the default theme wallpaper from `pcmanfm-qt --desktop-pref second` (works  but ok?) they won't see the wallpaper directory but themes dir. I tried to use symlinks in wallpaper.cfg but this didn't work.

1. abandon this idea
2. ship double wallpapers
3. else (fix symlinks? fix` wallpaper.cfg`?

**Review by tsujan — APPROVED** [review]
GTM

**Pull request merged**
