### PR TITLE
Style more plugins in KDE-Plasma theme

### PR DESCRIPTION
**Pull request by isf63**
- Adds top bar styling to Color Picker, and Status Notifier items

The top bar on Color Picker is not positioned correctly but https://github.com/lxqt/lxqt-panel/pull/2049 corrects that.

### CODE REVIEW

**Comment by isf63** [comment]
@stefonarch, when you get a chance could you review this?

**Comment by stefonarch** [comment]
It looks ok,  but for the notification area I'm unsure if we should really change a long standing theme, user might not like it.  Usually icons in notification area have no visible hover effect, expect tooltips ofc.

Afaik @yan12125 uses it, let's here others.

**Comment by yan12125** [comment]
Thanks for the work. It seems this change brings more benefits (easier to identify the target QToolButton) than issues (additional margin may require reorganizing the panel layout). Overall, I'm fine with this change.

> user might not like a change

I'm against a breaking change like https://github.com/lxqt/lxqt-themes/issues/69. This pull request is okay :)

PS. I don't use the color picker. Only status notifiers are tested.

**Comment by isf63** [comment]
Thanks for reviewing!
> I don't use the color picker.

For ColorPicker and Backlight, there exists a bug when panel size is greater than the icon size on several themes. I mentioned another PR that _I think_ is the fix.

**Comment by isf63** [comment]
Closing this because I've lost track of the multiple commits and merge conflicts. Will make a new PR.

**Pull request closed without merging**
